import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./Components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body>
        <ThemeProvider defaultTheme="dark" attribute="class">
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
